# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title EM algorithm for the Genetic problem
#' @name EM 
NULL

EM <- function(nc, ni, nt) {
    .Call('_SA23204174_EM', PACKAGE = 'SA23204174', nc, ni, nt)
}

